import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical Humanoid Robotics Crash Course',
      items: [
        'humanoid-robotics-course/01-introduction-to-humanoid-robotics',
        'humanoid-robotics-course/02-sensors-and-perception',
        'humanoid-robotics-course/03-actuators-and-movement',
        'humanoid-robotics-course/04-control-systems',
        'humanoid-robotics-course/05-path-planning-and-navigation',
      ],
    },
  ],
};

export default sidebars;
